### ISSUE TITLE
The service "alsatian_form.form_extension.extensible" has a dependency on a non-existent service "doctrine.odm.mong odb.document_manager".

### ISSUE THREAD

**Issue by bluppfisk** [Alsatian67/FormBundle#1]
Is this compatible with MySQL at all?

The service "alsatian_form.form_extension.extensible" has a dependency on a non-existent service "doctrine.odm.mongodb.document_manager".

edit: yes it is in fact, I had to comment out a line in your bundle's services.yml

```
    alsatian_form.form_event_subscriber.extensible:
        class: Alsatian\FormBundle\Form\Extensions\ExtensibleSubscriber
        public: false
        arguments: [%alsatian_form.parameters.extensible.enabled_Types%]
        calls:
            - [setEntityManager,["@doctrine.orm.entity_manager"]]
            #- [setDocumentManager,["@doctrine.odm.mongodb.document_manager"]]
```
